dir: 
  data: data
  figures:  figures
  results : results
files :
    exchanges_country_suffixes : data/exchanges_country_suffixes.csv
    results:
        all_best_lags : "results/all_best_lags.csv" 
signal: trade
stock:  MSFT
markets: 
    suffix:
        DE : ""
        GB : ""
        NL : ""
        UK : .L
        US : ""
  
location: 
    -DE
    -GB
    -NL
    -UK
    -US
test_date: 2010-01-04
open_time: 09:30:00
close_time: 16:00:00
