dir: 
  data: data
  figures:  figures
  results : results
files :
    exchanges_country_suffixes : data/exchanges_country_suffixes.csv
    results:
        all_best_lags : "results/all_best_lags.csv" 
signal: trade
stock: RDSa
old_stock: MSFT
markets: 
<<<<<<< HEAD
    suffix:
        DE : ""
        GB : ""
        NL : ""
        UK : .L
        US : ""
=======
    GB : L
    NL : AS
    US : N
>>>>>>> 9699c4d04f0d23da51aa6a5734eaad373afa9f5b
  
location: 
    -DE
    -GB
    -NL
    -UK
    -US
test_date: 2010-01-04
open_time: 09:30:00
close_time: 16:00:00
