dir: 
  data: data/markets
  figures:  figures
  results : results
files :
    exchanges_country_suffixes : data/exchanges_country_suffixes.csv
    results:
        all_best_lags : "results/lags_{}.csv" 
        liquidity : "results/liquidity.csv" 
signal: trade
stock: RDSa
old_stock: MSFT
markets: 
    list:
        - GB
        - US
        - NL
    suffix:
        GB : L
        NL : AS
        US : N
  
test_date: 2010-01-04
open_time: 09:30:00
close_time: 16:00:00
