dir: 
  data: data
  figures:  figures
  results : results
files :
    exchanges_country_suffixes : data/exchanges_country_suffixes.csv
    results:
        all_best_lags : "results/all_best_lags.csv" 
signal: trade
stock: RDSa
old_stock: MSFT
markets: 
    GB : L
    NL : AS
    US : N

  
location: 
    -DE
    -GB
    -NL
    -UK
    -US
test_date: 2010-01-04
open_time: 09:30:00
close_time: 16:00:00
