dir: 
  data: data/markets
  figures:  figures
  results : results
files :
    exchanges_country_suffixes : data/exchanges_country_suffixes.csv
    results:
        all_best_lags : "results/lags_{}.csv" 
        liquidity : "results/liquidity.csv" 
signal: trade
stock: RDSa
old_stock: MSFT
markets: 
    list:
        - GB
        - US
        - NL
    suffix:
        GB : L
        NL : AS
        US : N
  
  
distances : 
    NL :
        GB: 357
        US: 5570
        NL : 0
    GB: 
        NL: 357
        US: 5862
        GB : 0
    US:
        NL: 5570
        GB: 5862
        US: 0
        
test_date: 2010-01-04
open_time: 09:30:00
close_time: 16:00:00
